export const requisition_product_list = {
	"response_code": 200,
	"message": "Success.",
	"depot_name": "DHAKA DEPOT",
	"wh_id": "218",
	"wh_name": "DHAKA DEPOT : FGW",
	"product_list": [
		{
			"id": 1,
			"prod_id": "1001",
			"display_code": "ABT2",
			"prod_class": "550",
			"base_tp": "179.91",
			"base_vat": "31.3",
			"prod_name": "Adarbi 40 Tablet",
			"prod_code": "ABT2",
			"code_id": null,
			"com_pack_size": "20's",
			"com_pack_desc": "2X10's",
			"base_uom": "BOX",
			"req_current_stock": 0,
			"req_safety_stock": 100
		},
		{
			"id": 4,
			"prod_id": "1004",
			"display_code": "AXC1",
			"prod_class": "546",
			"base_tp": "270.61",
			"base_vat": "47.09",
			"prod_name": "AMX 250 Capsule",
			"prod_code": "AXC1",
			"code_id": null,
			"com_pack_size": "100's",
			"com_pack_desc": "10X10's",
			"base_uom": "BOX",
			"req_current_stock": 4,
			"req_safety_stock": 100
		},
		{
			"id": 74,
			"prod_id": "1074",
			"display_code": "LMT6",
			"prod_class": "541",
			"base_tp": "539.73",
			"base_vat": "93.91",
			"prod_name": "Lijenta-M 500 Tablet",
			"prod_code": "LMT6",
			"code_id": null,
			"com_pack_size": "60's",
			"com_pack_desc": "6X10's",
			"base_uom": "BOX",
			"req_current_stock": 70.46000000000001,
			"req_safety_stock": 100
		},
		{
			"id": 114,
			"prod_id": "1114",
			"display_code": "PRT1",
			"prod_class": "541",
			"base_tp": "224.89",
			"base_vat": "39.13",
			"prod_name": "Pandura 0.5 Tablet",
			"prod_code": "PRT1",
			"code_id": null,
			"com_pack_size": "50's",
			"com_pack_desc": "5X10's",
			"base_uom": "BOX",
			"req_current_stock": 97,
			"req_safety_stock": 100
		},
		{
			"id": 91,
			"prod_id": "1091",
			"display_code": "NVT1",
			"prod_class": "542",
			"base_tp": "299.85",
			"base_vat": "52.17",
			"prod_name": "Nimovo Tablet",
			"prod_code": "NVT1",
			"code_id": null,
			"com_pack_size": "40's",
			"com_pack_desc": "4X10's",
			"base_uom": "BOX",
			"req_current_stock": 133.7,
			"req_safety_stock": 100
		},
		{
			"id": 2,
			"prod_id": "1002",
			"display_code": "ABT3",
			"prod_class": "546",
			"base_tp": "329.84",
			"base_vat": "57.39",
			"prod_name": "Adarbi 80 Tablet",
			"prod_code": "ABT3",
			"code_id": null,
			"com_pack_size": "20's",
			"com_pack_desc": "2X10's",
			"base_uom": "BOX",
			"req_current_stock": 220,
			"req_safety_stock": 100
		},
		{
			"id": 121,
			"prod_id": "1121",
			"display_code": "RTT1",
			"prod_class": "541",
			"base_tp": "187.41",
			"base_vat": "32.61",
			"prod_name": "Rablet 20 Tablet",
			"prod_code": "RTT1",
			"code_id": null,
			"com_pack_size": "50's",
			"com_pack_desc": "5X10's",
			"base_uom": "BOX",
			"req_current_stock": 286,
			"req_safety_stock": 100
		},
		{
			"id": 88,
			"prod_id": "1088",
			"display_code": "MVT1",
			"prod_class": "541",
			"base_tp": "337.33",
			"base_vat": "58.7",
			"prod_name": "Montiva 10 Tablet",
			"prod_code": "MVT1",
			"code_id": null,
			"com_pack_size": "30's",
			"com_pack_desc": "3X10's",
			"base_uom": "BOX",
			"req_current_stock": 399.17100000000007,
			"req_safety_stock": 100
		},
		{
			"id": 36,
			"prod_id": "1036",
			"display_code": "DVS1",
			"prod_class": "542",
			"base_tp": "74.96",
			"base_vat": "13.04",
			"prod_name": "Doxiva Syrup",
			"prod_code": "DVS1",
			"code_id": null,
			"com_pack_size": "100 ml",
			"com_pack_desc": "1X1's",
			"base_uom": "BOX",
			"req_current_stock": 515,
			"req_safety_stock": 100
		},
		{
			"id": 43,
			"prod_id": "1043",
			"display_code": "EMT1",
			"prod_class": "541",
			"base_tp": "337.33",
			"base_vat": "58.7",
			"prod_name": "EmpaMet Tablet",
			"prod_code": "EMT1",
			"code_id": null,
			"com_pack_size": "30's",
			"com_pack_desc": "3X10's",
			"base_uom": "BOX",
			"req_current_stock": 519,
			"req_safety_stock": 100
		},
		{
			"id": 37,
			"prod_id": "1037",
			"display_code": "DVT3",
			"prod_class": "542",
			"base_tp": "374.81",
			"base_vat": "65.22",
			"prod_name": "Doxiva 400 Tablet",
			"prod_code": "DVT3",
			"code_id": null,
			"com_pack_size": "50's",
			"com_pack_desc": "5X10's",
			"base_uom": "BOX",
			"req_current_stock": 600,
			"req_safety_stock": 100
		},
		{
			"id": 103,
			"prod_id": "1103",
			"display_code": "NVI3",
			"prod_class": "542",
			"base_tp": "165.41",
			"base_vat": "28.78",
			"prod_name": "Nixon 1 g IV Injection",
			"prod_code": "NVI3",
			"code_id": null,
			"com_pack_size": "1's",
			"com_pack_desc": "1X1's",
			"base_uom": "BOX",
			"req_current_stock": 606,
			"req_safety_stock": 100
		},
		{
			"id": 75,
			"prod_id": "1075",
			"display_code": "LMT5",
			"prod_class": "541",
			"base_tp": "335.83",
			"base_vat": "58.43",
			"prod_name": "Lijenta-M 850 Tablet",
			"prod_code": "LMT5",
			"code_id": null,
			"com_pack_size": "32's",
			"com_pack_desc": "4X8's",
			"base_uom": "BOX",
			"req_current_stock": 622.5,
			"req_safety_stock": 100
		},
		{
			"id": 139,
			"prod_id": "1139",
			"display_code": "VNT3",
			"prod_class": "541",
			"base_tp": "299.85",
			"base_vat": "52.17",
			"prod_name": "V3N Tablet",
			"prod_code": "VNT3",
			"code_id": null,
			"com_pack_size": "50's",
			"com_pack_desc": "5X10's",
			"base_uom": "BOX",
			"req_current_stock": 636.9,
			"req_safety_stock": 100
		},
		{
			"id": 41,
			"prod_id": "1041",
			"display_code": "EPT3",
			"prod_class": "541",
			"base_tp": "562.22",
			"base_vat": "97.83",
			"prod_name": "Empa 10 Tablet",
			"prod_code": "EPT3",
			"code_id": null,
			"com_pack_size": "30's",
			"com_pack_desc": "2X15's",
			"base_uom": "BOX",
			"req_current_stock": 666.12,
			"req_safety_stock": 100
		},
		{
			"id": 124,
			"prod_id": "1124",
			"display_code": "RCC1",
			"prod_class": "546",
			"base_tp": "135.38",
			"base_vat": "23.56",
			"prod_name": "Receca  Capsule",
			"prod_code": "RCC1",
			"code_id": null,
			"com_pack_size": "30's",
			"com_pack_desc": "3X10's",
			"base_uom": "BOX",
			"req_current_stock": 728.34,
			"req_safety_stock": 100
		},
		{
			"id": 44,
			"prod_id": "1044",
			"display_code": "ENC1",
			"prod_class": "542",
			"base_tp": "359.82",
			"base_vat": "62.61",
			"prod_name": "Erdostin Capsule",
			"prod_code": "ENC1",
			"code_id": null,
			"com_pack_size": "32's",
			"com_pack_desc": "4X8's",
			"base_uom": "BOX",
			"req_current_stock": 784,
			"req_safety_stock": 100
		},
		{
			"id": 126,
			"prod_id": "1126",
			"display_code": "RRT2",
			"prod_class": "550",
			"base_tp": "299.85",
			"base_vat": "52.17",
			"prod_name": "Rovator 10 Tablet",
			"prod_code": "RRT2",
			"code_id": null,
			"com_pack_size": "20's",
			"com_pack_desc": "2X10's",
			"base_uom": "BOX",
			"req_current_stock": 834,
			"req_safety_stock": 100
		},
		{
			"id": 132,
			"prod_id": "1132",
			"display_code": "TRT1",
			"prod_class": "546",
			"base_tp": "112.44",
			"base_vat": "19.56",
			"prod_name": "Tamino ER Tablet",
			"prod_code": "TRT1",
			"code_id": null,
			"com_pack_size": "100's",
			"com_pack_desc": "10X10's",
			"base_uom": "BOX",
			"req_current_stock": 848,
			"req_safety_stock": 100
		},
		{
			"id": 30,
			"prod_id": "1030",
			"display_code": "DLT1",
			"prod_class": "546",
			"base_tp": "90.22",
			"base_vat": "15.7",
			"prod_name": "Danafil 50 Tablet",
			"prod_code": "DLT1",
			"code_id": null,
			"com_pack_size": "4's",
			"com_pack_desc": "1X4's",
			"base_uom": "BOX",
			"req_current_stock": 918,
			"req_safety_stock": 100
		},
		{
			"id": 127,
			"prod_id": "1127",
			"display_code": "RRT1",
			"prod_class": "550",
			"base_tp": "224.89",
			"base_vat": "39.13",
			"prod_name": "Rovator 5 Tablet",
			"prod_code": "RRT1",
			"code_id": null,
			"com_pack_size": "30's",
			"com_pack_desc": "3X10's",
			"base_uom": "BOX",
			"req_current_stock": 920,
			"req_safety_stock": 100
		},
		{
			"id": 8,
			"prod_id": "1008",
			"display_code": "ATS1",
			"prod_class": "546",
			"base_tp": "18.8",
			"base_vat": "3.27",
			"prod_name": "Arcet Syrup",
			"prod_code": "ATS1",
			"code_id": null,
			"com_pack_size": "60 ml",
			"com_pack_desc": "1X1's",
			"base_uom": "BOX",
			"req_current_stock": 921,
			"req_safety_stock": 100
		},
		{
			"id": 108,
			"prod_id": "1108",
			"display_code": "NVI2",
			"prod_class": "546",
			"base_tp": "112.78",
			"base_vat": "19.62",
			"prod_name": "Nixon 500 mg IV Injection",
			"prod_code": "NVI2",
			"code_id": null,
			"com_pack_size": "1's",
			"com_pack_desc": "1X1's",
			"base_uom": "BOX",
			"req_current_stock": 923,
			"req_safety_stock": 100
		},
		{
			"id": 102,
			"prod_id": "1102",
			"display_code": "NMI3",
			"prod_class": "546",
			"base_tp": "165.41",
			"base_vat": "28.78",
			"prod_name": "Nixon 1 gm IM",
			"prod_code": "NMI3",
			"code_id": null,
			"com_pack_size": "1's",
			"com_pack_desc": "1X1's",
			"base_uom": "BOX",
			"req_current_stock": 934,
			"req_safety_stock": 100
		},
		{
			"id": 82,
			"prod_id": "1082",
			"display_code": "LXC1",
			"prod_class": "546",
			"base_tp": "269.87",
			"base_vat": "46.96",
			"prod_name": "Lyrinex 50 Capsule",
			"prod_code": "LXC1",
			"code_id": null,
			"com_pack_size": "30's",
			"com_pack_desc": "3X10's",
			"base_uom": "BOX",
			"req_current_stock": 944.01,
			"req_safety_stock": 100
		},
		{
			"id": 97,
			"prod_id": "1097",
			"display_code": "NCS2",
			"prod_class": "546",
			"base_tp": "164.92",
			"base_vat": "28.7",
			"prod_name": "Niprolac Oral Solution",
			"prod_code": "NCS2",
			"code_id": null,
			"com_pack_size": "200 ml",
			"com_pack_desc": "1X1's",
			"base_uom": "BOX",
			"req_current_stock": 948,
			"req_safety_stock": 100
		},
		{
			"id": 101,
			"prod_id": "1101",
			"display_code": "NST1",
			"prod_class": "550",
			"base_tp": "149.93",
			"base_vat": "26.09",
			"prod_name": "Nitrogina SR Tablet",
			"prod_code": "NST1",
			"code_id": null,
			"com_pack_size": "50's",
			"com_pack_desc": "5X10's",
			"base_uom": "BOX",
			"req_current_stock": 949,
			"req_safety_stock": 100
		},
		{
			"id": 24,
			"prod_id": "1024",
			"display_code": "CST1",
			"prod_class": "542",
			"base_tp": "247.38",
			"base_vat": "43.04",
			"prod_name": "Carceva Plus Tablet",
			"prod_code": "CST1",
			"code_id": null,
			"com_pack_size": "30's",
			"com_pack_desc": "3X10's",
			"base_uom": "BOX",
			"req_current_stock": 959,
			"req_safety_stock": 100
		},
		{
			"id": 116,
			"prod_id": "1116",
			"display_code": "PRT3",
			"prod_class": "546",
			"base_tp": "224.89",
			"base_vat": "39.13",
			"prod_name": "Pandura 2 Tablet",
			"prod_code": "PRT3",
			"code_id": null,
			"com_pack_size": "30's",
			"com_pack_desc": "3X10's",
			"base_uom": "BOX",
			"req_current_stock": 960,
			"req_safety_stock": 100
		},
		{
			"id": 106,
			"prod_id": "1106",
			"display_code": "NVI4",
			"prod_class": "548",
			"base_tp": "240.6",
			"base_vat": "41.86",
			"prod_name": "Nixon 2 g IV Injection",
			"prod_code": "NVI4",
			"code_id": null,
			"com_pack_size": "1's",
			"com_pack_desc": "1X1's",
			"base_uom": "BOX",
			"req_current_stock": 972,
			"req_safety_stock": 100
		},
		{
			"id": 6,
			"prod_id": "1006",
			"display_code": "ASP1",
			"prod_class": "546",
			"base_tp": "58.47",
			"base_vat": "10.17",
			"prod_name": "AMX DS PFS",
			"prod_code": "ASP1",
			"code_id": null,
			"com_pack_size": "100 ml",
			"com_pack_desc": "1X1's",
			"base_uom": "BOX",
			"req_current_stock": 976,
			"req_safety_stock": 100
		},
		{
			"id": 76,
			"prod_id": "1076",
			"display_code": "LMX1",
			"prod_class": "546",
			"base_tp": "203.9",
			"base_vat": "35.48",
			"prod_name": "Lijenta-MX 2.5 Tablet",
			"prod_code": "LMX1",
			"code_id": null,
			"com_pack_size": "16's",
			"com_pack_desc": "2X8's",
			"base_uom": "BOX",
			"req_current_stock": 977,
			"req_safety_stock": 100
		},
		{
			"id": 85,
			"prod_id": "1085",
			"display_code": "MVI2",
			"prod_class": "542",
			"base_tp": "899.55",
			"base_vat": "156.52",
			"prod_name": "Meroxin 1 g IV Injection",
			"prod_code": "MVI2",
			"code_id": null,
			"com_pack_size": "1's",
			"com_pack_desc": "1X1's",
			"base_uom": "BOX",
			"req_current_stock": 980,
			"req_safety_stock": 100
		},
		{
			"id": 136,
			"prod_id": "1136",
			"display_code": "TTT1",
			"prod_class": "546",
			"base_tp": "112.89",
			"base_vat": "19.64",
			"prod_name": "Thixtra Tablet",
			"prod_code": "TTT1",
			"code_id": null,
			"com_pack_size": "30's",
			"com_pack_desc": "3X10's",
			"base_uom": "BOX",
			"req_current_stock": 980.64,
			"req_safety_stock": 100
		},
		{
			"id": 62,
			"prod_id": "1062",
			"display_code": "FTM1",
			"prod_class": "546",
			"base_tp": "59.97",
			"base_vat": "10.43",
			"prod_name": "Flurodent Mouthwash",
			"prod_code": "FTM1",
			"code_id": null,
			"com_pack_size": "120 ml",
			"com_pack_desc": "1X1's",
			"base_uom": "BOX",
			"req_current_stock": 981,
			"req_safety_stock": 100
		},
		{
			"id": 86,
			"prod_id": "1086",
			"display_code": "MVI1",
			"prod_class": "548",
			"base_tp": "487.26",
			"base_vat": "84.78",
			"prod_name": "Meroxin 500 mg IV Injection",
			"prod_code": "MVI1",
			"code_id": null,
			"com_pack_size": "1's",
			"com_pack_desc": "1X1's",
			"base_uom": "BOX",
			"req_current_stock": 990,
			"req_safety_stock": 100
		},
		{
			"id": 78,
			"prod_id": "1078",
			"display_code": "LST2",
			"prod_class": "546",
			"base_tp": "112.44",
			"base_vat": "19.56",
			"prod_name": "Losarva 25 Tablet",
			"prod_code": "LST2",
			"code_id": null,
			"com_pack_size": "50's",
			"com_pack_desc": "5X10's",
			"base_uom": "BOX",
			"req_current_stock": 994,
			"req_safety_stock": 100
		},
		{
			"id": 66,
			"prod_id": "1066",
			"display_code": "HNC1",
			"prod_class": "546",
			"base_tp": "166.42",
			"base_vat": "28.96",
			"prod_name": "Halopen 250 Capsule",
			"prod_code": "HNC1",
			"code_id": null,
			"com_pack_size": "40'S",
			"com_pack_desc": "10X4's",
			"base_uom": "BOX",
			"req_current_stock": 996,
			"req_safety_stock": 100
		},
		{
			"id": 96,
			"prod_id": "1096",
			"display_code": "NCS1",
			"prod_class": "542",
			"base_tp": "90.22",
			"base_vat": "15.7",
			"prod_name": "Niprolac Oral Solution",
			"prod_code": "NCS1",
			"code_id": null,
			"com_pack_size": "100 ml",
			"com_pack_desc": "1X1's",
			"base_uom": "BOX",
			"req_current_stock": 996,
			"req_safety_stock": 100
		},
		{
			"id": 98,
			"prod_id": "1098",
			"display_code": "NTT1",
			"prod_class": "546",
			"base_tp": "225.56",
			"base_vat": "39.25",
			"prod_name": "Nitide 500 Tablet",
			"prod_code": "NTT1",
			"code_id": null,
			"com_pack_size": "30's",
			"com_pack_desc": "3X10's",
			"base_uom": "BOX",
			"req_current_stock": 997.66,
			"req_safety_stock": 100
		},
		{
			"id": 16,
			"prod_id": "1016",
			"display_code": "BNO1",
			"prod_class": "545",
			"base_tp": "104.95",
			"base_vat": "18.26",
			"prod_name": "Bactropen Ointment",
			"prod_code": "BNO1",
			"code_id": null,
			"com_pack_size": "1's",
			"com_pack_desc": "1X1's",
			"base_uom": "BOX",
			"req_current_stock": 1000,
			"req_safety_stock": 100
		},
		{
			"id": 111,
			"prod_id": "1111",
			"display_code": "OLC1",
			"prod_class": "546",
			"base_tp": "225.56",
			"base_vat": "39.25",
			"prod_name": "Ostriol Capsule",
			"prod_code": "OLC1",
			"code_id": null,
			"com_pack_size": "30's",
			"com_pack_desc": "3X10's",
			"base_uom": "BOX",
			"req_current_stock": 1001.394,
			"req_safety_stock": 100
		},
		{
			"id": 31,
			"prod_id": "1031",
			"display_code": "DGC1",
			"prod_class": "546",
			"base_tp": "166.12",
			"base_vat": "28.9",
			"prod_name": "Defungi 150 Capsule",
			"prod_code": "DGC1",
			"code_id": null,
			"com_pack_size": "10's",
			"com_pack_desc": "1X10's",
			"base_uom": "BOX",
			"req_current_stock": 1003,
			"req_safety_stock": 100
		},
		{
			"id": 55,
			"prod_id": "1055",
			"display_code": "FRC2",
			"prod_class": "546",
			"base_tp": "301.89",
			"base_vat": "52.53",
			"prod_name": "Fixpro 400 Capsule",
			"prod_code": "FRC2",
			"code_id": null,
			"com_pack_size": "8's",
			"com_pack_desc": "2X4's",
			"base_uom": "BOX",
			"req_current_stock": 1004,
			"req_safety_stock": 100
		},
		{
			"id": 147,
			"prod_id": "1147",
			"display_code": "XVI1",
			"prod_class": "546",
			"base_tp": "93.7",
			"base_vat": "16.3",
			"prod_name": "Xinarox 750 mg IM/IV Injection",
			"prod_code": "XVI1",
			"code_id": null,
			"com_pack_size": "1's",
			"com_pack_desc": "1X1's",
			"base_uom": "BOX",
			"req_current_stock": 1004,
			"req_safety_stock": 100
		},
		{
			"id": 694,
			"prod_id": "2014",
			"display_code": "FGT1",
			"prod_class": "546",
			"base_tp": "1724",
			"base_vat": "0",
			"prod_name": "Fluvigan 200 Tablet",
			"prod_code": "FGT1",
			"code_id": null,
			"com_pack_size": "10's",
			"com_pack_desc": "1X10's",
			"base_uom": "BOX",
			"req_current_stock": 1005,
			"req_safety_stock": 100
		},
		{
			"id": 32,
			"prod_id": "1032",
			"display_code": "DGC2",
			"prod_class": "546",
			"base_tp": "181.26",
			"base_vat": "31.54",
			"prod_name": "Defungi 50 Capsule",
			"prod_code": "DGC2",
			"code_id": null,
			"com_pack_size": "30's",
			"com_pack_desc": "3X10's",
			"base_uom": "BOX",
			"req_current_stock": 1005.003,
			"req_safety_stock": 100
		},
		{
			"id": 5,
			"prod_id": "1005",
			"display_code": "AXC2",
			"prod_class": "546",
			"base_tp": "254.12",
			"base_vat": "44.22",
			"prod_name": "AMX 500 Capsule",
			"prod_code": "AXC2",
			"code_id": null,
			"com_pack_size": "50's",
			"com_pack_desc": "5X10's",
			"base_uom": "BOX",
			"req_current_stock": 1006,
			"req_safety_stock": 100
		},
		{
			"id": 118,
			"prod_id": "1118",
			"display_code": "PST4",
			"prod_class": "546",
			"base_tp": "224.89",
			"base_vat": "39.13",
			"prod_name": "Pansos 40 Tablet",
			"prod_code": "PST4",
			"code_id": null,
			"com_pack_size": "50's",
			"com_pack_desc": "5X10's",
			"base_uom": "BOX",
			"req_current_stock": 1006,
			"req_safety_stock": 100
		},
		{
			"id": 48,
			"prod_id": "1048",
			"display_code": "ERT2",
			"prod_class": "546",
			"base_tp": "180.36",
			"base_vat": "31.38",
			"prod_name": "Esotor 40 Tablet",
			"prod_code": "ERT2",
			"code_id": null,
			"com_pack_size": "30's",
			"com_pack_desc": "3X10's",
			"base_uom": "BOX",
			"req_current_stock": 1006.61,
			"req_safety_stock": 100
		},
		{
			"id": 7,
			"prod_id": "1007",
			"display_code": "AXP1",
			"prod_class": "546",
			"base_tp": "35.69",
			"base_vat": "6.21",
			"prod_name": "AMX PFS",
			"prod_code": "AXP1",
			"code_id": null,
			"com_pack_size": "100 ml",
			"com_pack_desc": "1X1's",
			"base_uom": "BOX",
			"req_current_stock": 1011,
			"req_safety_stock": 100
		},
		{
			"id": 27,
			"prod_id": "1027",
			"display_code": "CSP1",
			"prod_class": "546",
			"base_tp": "101.2",
			"base_vat": "17.61",
			"prod_name": "Cefracef DS PFS",
			"prod_code": "CSP1",
			"code_id": null,
			"com_pack_size": "100 ml",
			"com_pack_desc": "1X1's",
			"base_uom": "BOX",
			"req_current_stock": 1011,
			"req_safety_stock": 100
		},
		{
			"id": 50,
			"prod_id": "1050",
			"display_code": "EBT2",
			"prod_class": "546",
			"base_tp": "270.76",
			"base_vat": "47.11",
			"prod_name": "Etrib 90 Tablet",
			"prod_code": "EBT2",
			"code_id": null,
			"com_pack_size": "30's",
			"com_pack_desc": "3X10's",
			"base_uom": "BOX",
			"req_current_stock": 1011.94,
			"req_safety_stock": 100
		},
		{
			"id": 115,
			"prod_id": "1115",
			"display_code": "PRT2",
			"prod_class": "546",
			"base_tp": "299.85",
			"base_vat": "52.17",
			"prod_name": "Pandura 1 Tablet",
			"prod_code": "PRT2",
			"code_id": null,
			"com_pack_size": "50's",
			"com_pack_desc": "5X10's",
			"base_uom": "BOX",
			"req_current_stock": 1013,
			"req_safety_stock": 100
		},
		{
			"id": 57,
			"prod_id": "1057",
			"display_code": "FSP1",
			"prod_class": "546",
			"base_tp": "209.9",
			"base_vat": "36.52",
			"prod_name": "Fixpro DS PFS",
			"prod_code": "FSP1",
			"code_id": null,
			"com_pack_size": "50 ml",
			"com_pack_desc": "1X1's",
			"base_uom": "BOX",
			"req_current_stock": 1013,
			"req_safety_stock": 100
		},
		{
			"id": 135,
			"prod_id": "1135",
			"display_code": "TNT1",
			"prod_class": "546",
			"base_tp": "119.94",
			"base_vat": "20.87",
			"prod_name": "Tamino Tablet",
			"prod_code": "TNT1",
			"code_id": null,
			"com_pack_size": "200's",
			"com_pack_desc": "20X10's",
			"base_uom": "BOX",
			"req_current_stock": 1018.5,
			"req_safety_stock": 100
		},
		{
			"id": 49,
			"prod_id": "1049",
			"display_code": "EBT1",
			"prod_class": "546",
			"base_tp": "157.42",
			"base_vat": "27.39",
			"prod_name": "Etrib 60 Tablet",
			"prod_code": "EBT1",
			"code_id": null,
			"com_pack_size": "30's",
			"com_pack_desc": "3X10's",
			"base_uom": "BOX",
			"req_current_stock": 1020,
			"req_safety_stock": 100
		},
		{
			"id": 141,
			"prod_id": "1141",
			"display_code": "VSS1",
			"prod_class": "546",
			"base_tp": "67.47",
			"base_vat": "11.74",
			"prod_name": "Visnil Syrup",
			"prod_code": "VSS1",
			"code_id": null,
			"com_pack_size": "1's",
			"com_pack_desc": "1X1's",
			"base_uom": "BOX",
			"req_current_stock": 1020,
			"req_safety_stock": 100
		},
		{
			"id": 54,
			"prod_id": "1054",
			"display_code": "FRC3",
			"prod_class": "542",
			"base_tp": "314.84",
			"base_vat": "54.78",
			"prod_name": "Fixpro 200 Capsule",
			"prod_code": "FRC3",
			"code_id": null,
			"com_pack_size": "12's",
			"com_pack_desc": "2X6's",
			"base_uom": "BOX",
			"req_current_stock": 1022,
			"req_safety_stock": 100
		},
		{
			"id": 134,
			"prod_id": "1134",
			"display_code": "TNS1",
			"prod_class": "546",
			"base_tp": "15.51",
			"base_vat": "2.7",
			"prod_name": "Tamino Suspension",
			"prod_code": "TNS1",
			"code_id": null,
			"com_pack_size": "60 ml",
			"com_pack_desc": "1X1's",
			"base_uom": "BOX",
			"req_current_stock": 1022,
			"req_safety_stock": 100
		},
		{
			"id": 80,
			"prod_id": "1080",
			"display_code": "LLT1",
			"prod_class": "550",
			"base_tp": "258.62",
			"base_vat": "45",
			"prod_name": "Losarva Plus Tablet",
			"prod_code": "LLT1",
			"code_id": null,
			"com_pack_size": "50's",
			"com_pack_desc": "5X10's",
			"base_uom": null,
			"req_current_stock": 1025,
			"req_safety_stock": 100
		},
		{
			"id": 10,
			"prod_id": "1010",
			"display_code": "ATN1",
			"prod_class": "541",
			"base_tp": "187.41",
			"base_vat": "32.61",
			"prod_name": "Avamist Nasal Spray",
			"prod_code": "ATN1",
			"code_id": null,
			"com_pack_size": "1's",
			"com_pack_desc": "1X1's",
			"base_uom": "BOX",
			"req_current_stock": 1027,
			"req_safety_stock": 100
		},
		{
			"id": 25,
			"prod_id": "1025",
			"display_code": "CFC1",
			"prod_class": "546",
			"base_tp": "147.3",
			"base_vat": "25.63",
			"prod_name": "Cefracef 250 Capsule",
			"prod_code": "CFC1",
			"code_id": null,
			"com_pack_size": "30's",
			"com_pack_desc": "5X6's",
			"base_uom": "BOX",
			"req_current_stock": 1033,
			"req_safety_stock": 100
		},
		{
			"id": 20,
			"prod_id": "1020",
			"display_code": "BTS1",
			"prod_class": "546",
			"base_tp": "30.07",
			"base_vat": "5.23",
			"prod_name": "Broculyt Syrup",
			"prod_code": "BTS1",
			"code_id": null,
			"com_pack_size": "100 ml",
			"com_pack_desc": "1X1's",
			"base_uom": "BOX",
			"req_current_stock": 1035,
			"req_safety_stock": 100
		},
		{
			"id": 38,
			"prod_id": "1038",
			"display_code": "DRT1",
			"prod_class": "542",
			"base_tp": "56.22",
			"base_vat": "9.78",
			"prod_name": "D-Star 2000 Tablet",
			"prod_code": "DRT1",
			"code_id": null,
			"com_pack_size": "30's",
			"com_pack_desc": "3X10's",
			"base_uom": "BOX",
			"req_current_stock": 1035,
			"req_safety_stock": 100
		},
		{
			"id": 110,
			"prod_id": "1110",
			"display_code": "ONC2",
			"prod_class": "546",
			"base_tp": "240.48",
			"base_vat": "41.84",
			"prod_name": "Omecron 40 Capsule",
			"prod_code": "ONC2",
			"code_id": null,
			"com_pack_size": "40's",
			"com_pack_desc": "5X8's",
			"base_uom": "BOX",
			"req_current_stock": 1036,
			"req_safety_stock": 100
		},
		{
			"id": 69,
			"prod_id": "1069",
			"display_code": "HNG1",
			"prod_class": "546",
			"base_tp": "112.44",
			"base_vat": "19.56",
			"prod_name": "Handsan Hand Sanitizer Gel",
			"prod_code": "HNG1",
			"code_id": null,
			"com_pack_size": "100 ml",
			"com_pack_desc": "1X1's",
			"base_uom": "BOX",
			"req_current_stock": 1038,
			"req_safety_stock": 100
		},
		{
			"id": 145,
			"prod_id": "1145",
			"display_code": "XXT1",
			"prod_class": "546",
			"base_tp": "225.61",
			"base_vat": "39.26",
			"prod_name": "Xinarox 250 Tablet",
			"prod_code": "XXT1",
			"code_id": null,
			"com_pack_size": "12's",
			"com_pack_desc": "2X6's",
			"base_uom": "BOX",
			"req_current_stock": 1038,
			"req_safety_stock": 100
		},
		{
			"id": 107,
			"prod_id": "1107",
			"display_code": "NMI2",
			"prod_class": "548",
			"base_tp": "112.78",
			"base_vat": "19.62",
			"prod_name": "Nixon 500 IM",
			"prod_code": "NMI2",
			"code_id": null,
			"com_pack_size": "1's",
			"com_pack_desc": "1X1's",
			"base_uom": "BOX",
			"req_current_stock": 1048,
			"req_safety_stock": 100
		},
		{
			"id": 12,
			"prod_id": "1012",
			"display_code": "ART2",
			"prod_class": "546",
			"base_tp": "270.61",
			"base_vat": "47.09",
			"prod_name": "Avator 20 Tablet",
			"prod_code": "ART2",
			"code_id": null,
			"com_pack_size": "20's",
			"com_pack_desc": "2X10's",
			"base_uom": "BOX",
			"req_current_stock": 1049,
			"req_safety_stock": 100
		},
		{
			"id": 119,
			"prod_id": "1119",
			"display_code": "PTS1",
			"prod_class": "546",
			"base_tp": "26.32",
			"base_vat": "4.58",
			"prod_name": "Prokinet Suspension",
			"prod_code": "PTS1",
			"code_id": null,
			"com_pack_size": "60 ml",
			"com_pack_desc": "1X1's",
			"base_uom": "BOX",
			"req_current_stock": 1050,
			"req_safety_stock": 100
		},
		{
			"id": 83,
			"prod_id": "1083",
			"display_code": "LXC2",
			"prod_class": "546",
			"base_tp": "359.82",
			"base_vat": "62.61",
			"prod_name": "Lyrinex 75 Capsule",
			"prod_code": "LXC2",
			"code_id": null,
			"com_pack_size": "30's",
			"com_pack_desc": "3X10's",
			"base_uom": "BOX",
			"req_current_stock": 1050,
			"req_safety_stock": 100
		},
		{
			"id": 89,
			"prod_id": "1089",
			"display_code": "MVT3",
			"prod_class": "546",
			"base_tp": "134.93",
			"base_vat": "23.48",
			"prod_name": "Montiva 4 Tablet",
			"prod_code": "MVT3",
			"code_id": null,
			"com_pack_size": "30's",
			"com_pack_desc": "3X10's",
			"base_uom": "BOX",
			"req_current_stock": 1054.33,
			"req_safety_stock": 100
		},
		{
			"id": 177,
			"prod_id": "1177",
			"display_code": "OFS1",
			"prod_class": "545",
			"base_tp": "74.96",
			"base_vat": "13.04",
			"prod_name": "OxyFast Nasal Spray",
			"prod_code": "OFS1",
			"code_id": null,
			"com_pack_size": "1's",
			"com_pack_desc": "1X1's",
			"base_uom": "BOX",
			"req_current_stock": 1060,
			"req_safety_stock": 100
		},
		{
			"id": 51,
			"prod_id": "1051",
			"display_code": "FNC1",
			"prod_class": "546",
			"base_tp": "146.18",
			"base_vat": "25.44",
			"prod_name": "Fenticona Vaginal Cream",
			"prod_code": "FNC1",
			"code_id": null,
			"com_pack_size": "30 gm",
			"com_pack_desc": "1X1's",
			"base_uom": "BOX",
			"req_current_stock": 1068,
			"req_safety_stock": 100
		},
		{
			"id": 125,
			"prod_id": "1125",
			"display_code": "RVT1",
			"prod_class": "546",
			"base_tp": "224.89",
			"base_vat": "39.13",
			"prod_name": "Revalon Tablet",
			"prod_code": "RVT1",
			"code_id": null,
			"com_pack_size": "10's",
			"com_pack_desc": "1X10's",
			"base_uom": "BOX",
			"req_current_stock": 1070,
			"req_safety_stock": 100
		},
		{
			"id": 84,
			"prod_id": "1084",
			"display_code": "MRC1",
			"prod_class": "545",
			"base_tp": "224.89",
			"base_vat": "39.13",
			"prod_name": "Mevigut SR Capsule",
			"prod_code": "MRC1",
			"code_id": null,
			"com_pack_size": "30's",
			"com_pack_desc": "3X10's",
			"base_uom": "BOX",
			"req_current_stock": 1071,
			"req_safety_stock": 100
		},
		{
			"id": 117,
			"prod_id": "1117",
			"display_code": "PST3",
			"prod_class": "546",
			"base_tp": "149.93",
			"base_vat": "26.09",
			"prod_name": "Pansos 20 Tablet",
			"prod_code": "PST3",
			"code_id": null,
			"com_pack_size": "50's",
			"com_pack_desc": "5X10's",
			"base_uom": "BOX",
			"req_current_stock": 1080,
			"req_safety_stock": 100
		},
		{
			"id": 146,
			"prod_id": "1146",
			"display_code": "XXT2",
			"prod_class": "546",
			"base_tp": "203.03",
			"base_vat": "35.33",
			"prod_name": "Xinarox 500 Tablet",
			"prod_code": "XXT2",
			"code_id": null,
			"com_pack_size": "6's",
			"com_pack_desc": "1X6's",
			"base_uom": "BOX",
			"req_current_stock": 1083,
			"req_safety_stock": 100
		},
		{
			"id": 81,
			"prod_id": "1081",
			"display_code": "LRT1",
			"prod_class": "550",
			"base_tp": "187.41",
			"base_vat": "32.61",
			"prod_name": "Lovapres 5 Tablet",
			"prod_code": "LRT1",
			"code_id": null,
			"com_pack_size": "50's",
			"com_pack_desc": "5X10's",
			"base_uom": "BOX",
			"req_current_stock": 1091,
			"req_safety_stock": 100
		},
		{
			"id": 60,
			"prod_id": "1060",
			"display_code": "FCT1",
			"prod_class": "550",
			"base_tp": "271.89",
			"base_vat": "47.31",
			"prod_name": "Florocin 500 Tablet",
			"prod_code": "FCT1",
			"code_id": null,
			"com_pack_size": "30's",
			"com_pack_desc": "3X10's",
			"base_uom": "BOX",
			"req_current_stock": 1095.677,
			"req_safety_stock": 100
		},
		{
			"id": 67,
			"prod_id": "1067",
			"display_code": "HNC2",
			"prod_class": "546",
			"base_tp": "210.52",
			"base_vat": "36.63",
			"prod_name": "Halopen 500 Capsule",
			"prod_code": "HNC2",
			"code_id": null,
			"com_pack_size": "28's",
			"com_pack_desc": "7X4's",
			"base_uom": "BOX",
			"req_current_stock": 1095.85,
			"req_safety_stock": 100
		},
		{
			"id": 90,
			"prod_id": "1090",
			"display_code": "MVT2",
			"prod_class": "546",
			"base_tp": "179.91",
			"base_vat": "31.3",
			"prod_name": "Montiva 5 Tablet",
			"prod_code": "MVT2",
			"code_id": null,
			"com_pack_size": "30's",
			"com_pack_desc": "3X10's",
			"base_uom": "BOX",
			"req_current_stock": 1099.34,
			"req_safety_stock": 100
		},
		{
			"id": 131,
			"prod_id": "1131",
			"display_code": "SNG1",
			"prod_class": "546",
			"base_tp": "44.97",
			"base_vat": "7.82",
			"prod_name": "Symbiotrin Oral Gel",
			"prod_code": "SNG1",
			"code_id": null,
			"com_pack_size": "1's",
			"com_pack_desc": "1X1's",
			"base_uom": "BOX",
			"req_current_stock": 1104,
			"req_safety_stock": 100
		},
		{
			"id": 33,
			"prod_id": "1033",
			"display_code": "DCT1",
			"prod_class": "546",
			"base_tp": "449.78",
			"base_vat": "78.26",
			"prod_name": "Diacana Tablet",
			"prod_code": "DCT1",
			"code_id": null,
			"com_pack_size": "10's",
			"com_pack_desc": "1X10's",
			"base_uom": "BOX",
			"req_current_stock": 1137,
			"req_safety_stock": 100
		},
		{
			"id": 65,
			"prod_id": "1065",
			"display_code": "GNT4",
			"prod_class": "542",
			"base_tp": "224.89",
			"base_vat": "39.13",
			"prod_name": "Glucomin 850 Tablet",
			"prod_code": "GNT4",
			"code_id": null,
			"com_pack_size": "50's",
			"com_pack_desc": "5X10's",
			"base_uom": "BOX",
			"req_current_stock": 1143.9,
			"req_safety_stock": 100
		},
		{
			"id": 3,
			"prod_id": "1003",
			"display_code": "APT1",
			"prod_class": "542",
			"base_tp": "188.09",
			"base_vat": "32.73",
			"prod_name": "Altrip Tablet",
			"prod_code": "APT1",
			"code_id": null,
			"com_pack_size": "10's",
			"com_pack_desc": "1X10's",
			"base_uom": "BOX",
			"req_current_stock": 1154,
			"req_safety_stock": 100
		},
		{
			"id": 53,
			"prod_id": "1053",
			"display_code": "FNS1",
			"prod_class": "546",
			"base_tp": "36.09",
			"base_vat": "6.28",
			"prod_name": "Fexten Suspension",
			"prod_code": "FNS1",
			"code_id": null,
			"com_pack_size": "50 ml",
			"com_pack_desc": "1X1's",
			"base_uom": "BOX",
			"req_current_stock": 1173,
			"req_safety_stock": 100
		},
		{
			"id": 87,
			"prod_id": "1087",
			"display_code": "MRT3",
			"prod_class": "542",
			"base_tp": "269.87",
			"base_vat": "46.96",
			"prod_name": "Metavas MR Tablet",
			"prod_code": "MRT3",
			"code_id": null,
			"com_pack_size": "60's",
			"com_pack_desc": "6X10's",
			"base_uom": "BOX",
			"req_current_stock": 1280.25,
			"req_safety_stock": 100
		},
		{
			"id": 148,
			"prod_id": "1148",
			"display_code": "XVT1",
			"prod_class": "541",
			"base_tp": "269.87",
			"base_vat": "46.96",
			"prod_name": "Xinarox CV 250 Tablet",
			"prod_code": "XVT1",
			"code_id": null,
			"com_pack_size": "12's",
			"com_pack_desc": "2X6's",
			"base_uom": "BOX",
			"req_current_stock": 1306,
			"req_safety_stock": 100
		},
		{
			"id": 70,
			"prod_id": "1070",
			"display_code": "ITT1",
			"prod_class": "542",
			"base_tp": "135.38",
			"base_vat": "23.56",
			"prod_name": "Irobest Tablet",
			"prod_code": "ITT1",
			"code_id": null,
			"com_pack_size": "60's",
			"com_pack_desc": "6X10's",
			"base_uom": "BOX",
			"req_current_stock": 1356.31,
			"req_safety_stock": 100
		},
		{
			"id": 39,
			"prod_id": "1039",
			"display_code": "DRC1",
			"prod_class": "542",
			"base_tp": "149.93",
			"base_vat": "26.09",
			"prod_name": "D-Star 20000 Capsule",
			"prod_code": "DRC1",
			"code_id": null,
			"com_pack_size": "10's",
			"com_pack_desc": "1X10's",
			"base_uom": "BOX",
			"req_current_stock": 1479,
			"req_safety_stock": 100
		},
		{
			"id": 40,
			"prod_id": "1040",
			"display_code": "DRC2",
			"prod_class": "541",
			"base_tp": "209.9",
			"base_vat": "36.52",
			"prod_name": "D-Star 40000 Capsule",
			"prod_code": "DRC2",
			"code_id": null,
			"com_pack_size": "8's",
			"com_pack_desc": "1X8's",
			"base_uom": "BOX",
			"req_current_stock": 1508,
			"req_safety_stock": 100
		},
		{
			"id": 113,
			"prod_id": "1113",
			"display_code": "OPD1",
			"prod_class": "542",
			"base_tp": "29.99",
			"base_vat": "5.22",
			"prod_name": "Oxydrop Paediatric Nasal Drops",
			"prod_code": "OPD1",
			"code_id": null,
			"com_pack_size": "10 ml",
			"com_pack_desc": "1X1's",
			"base_uom": "BOX",
			"req_current_stock": 1532,
			"req_safety_stock": 100
		},
		{
			"id": 17,
			"prod_id": "1017",
			"display_code": "BTT1",
			"prod_class": "541",
			"base_tp": "337.33",
			"base_vat": "58.7",
			"prod_name": "Bilfast Tablet",
			"prod_code": "BTT1",
			"code_id": null,
			"com_pack_size": "30'S",
			"com_pack_desc": "3X10's",
			"base_uom": "BOX",
			"req_current_stock": 1651,
			"req_safety_stock": 100
		},
		{
			"id": 149,
			"prod_id": "1149",
			"display_code": "XVT2",
			"prod_class": "541",
			"base_tp": "299.85",
			"base_vat": "52.17",
			"prod_name": "Xinarox CV 500 Tablet",
			"prod_code": "XVT2",
			"code_id": null,
			"com_pack_size": "8's",
			"com_pack_desc": "2X4's",
			"base_uom": "BOX",
			"req_current_stock": 1689,
			"req_safety_stock": 100
		},
		{
			"id": 73,
			"prod_id": "1073",
			"display_code": "LMT3",
			"prod_class": "542",
			"base_tp": "179.91",
			"base_vat": "31.3",
			"prod_name": "Lijenta-M 1000 Tablet",
			"prod_code": "LMT3",
			"code_id": null,
			"com_pack_size": "16's",
			"com_pack_desc": "2X8's",
			"base_uom": "BOX",
			"req_current_stock": 1721,
			"req_safety_stock": 100
		},
		{
			"id": 112,
			"prod_id": "1112",
			"display_code": "OPD2",
			"prod_class": "542",
			"base_tp": "33.73",
			"base_vat": "5.87",
			"prod_name": "Oxydrop Nasal Drops",
			"prod_code": "OPD2",
			"code_id": null,
			"com_pack_size": "10 ml",
			"com_pack_desc": "1X1's",
			"base_uom": "BOX",
			"req_current_stock": 1813,
			"req_safety_stock": 100
		},
		{
			"id": 64,
			"prod_id": "1064",
			"display_code": "GNT3",
			"prod_class": "542",
			"base_tp": "149.93",
			"base_vat": "26.09",
			"prod_name": "Glucomin 500 Tablet",
			"prod_code": "GNT3",
			"code_id": null,
			"com_pack_size": "50's",
			"com_pack_desc": "5X10's",
			"base_uom": "BOX",
			"req_current_stock": 1881,
			"req_safety_stock": 100
		},
		{
			"id": 52,
			"prod_id": "1052",
			"display_code": "FNT4",
			"prod_class": "542",
			"base_tp": "157.42",
			"base_vat": "27.39",
			"prod_name": "Fexten 120 Tablet",
			"prod_code": "FNT4",
			"code_id": null,
			"com_pack_size": "30's",
			"com_pack_desc": "3X10's",
			"base_uom": "BOX",
			"req_current_stock": 1919,
			"req_safety_stock": 100
		},
		{
			"id": 22,
			"prod_id": "1022",
			"display_code": "CSC2",
			"prod_class": "546",
			"base_tp": "89.96",
			"base_vat": "15.65",
			"prod_name": "Camphor Plus Cream",
			"prod_code": "CSC2",
			"code_id": null,
			"com_pack_size": "25 gm",
			"com_pack_desc": "1X1's",
			"base_uom": "BOX",
			"req_current_stock": 1995,
			"req_safety_stock": 100
		},
		{
			"id": 47,
			"prod_id": "1047",
			"display_code": "ERC2",
			"prod_class": "546",
			"base_tp": "269.87",
			"base_vat": "46.96",
			"prod_name": "Esotor 40 Capsule",
			"prod_code": "ERC2",
			"code_id": null,
			"com_pack_size": "40's",
			"com_pack_desc": "4X10's",
			"base_uom": "BOX",
			"req_current_stock": 1999,
			"req_safety_stock": 100
		},
		{
			"id": 56,
			"prod_id": "1056",
			"display_code": "FRP1",
			"prod_class": "542",
			"base_tp": "147.17",
			"base_vat": "25.61",
			"prod_name": "Fixpro PFS",
			"prod_code": "FRP1",
			"code_id": null,
			"com_pack_size": "50 ml",
			"com_pack_desc": "1X1's",
			"base_uom": "BOX",
			"req_current_stock": 2005.9,
			"req_safety_stock": 100
		},
		{
			"id": 28,
			"prod_id": "1028",
			"display_code": "CFP1",
			"prod_class": "546",
			"base_tp": "60.38",
			"base_vat": "10.51",
			"prod_name": "Cefracef PFS",
			"prod_code": "CFP1",
			"code_id": null,
			"com_pack_size": "100 ml",
			"com_pack_desc": "1X1's",
			"base_uom": "BOX",
			"req_current_stock": 2013,
			"req_safety_stock": 100
		},
		{
			"id": 122,
			"prod_id": "1122",
			"display_code": "RCG1",
			"prod_class": "546",
			"base_tp": "157.42",
			"base_vat": "27.39",
			"prod_name": "Receca  10 GFS",
			"prod_code": "RCG1",
			"code_id": null,
			"com_pack_size": "30's",
			"com_pack_desc": "1X30's",
			"base_uom": "BOX",
			"req_current_stock": 2017,
			"req_safety_stock": 100
		},
		{
			"id": 61,
			"prod_id": "1061",
			"display_code": "FCP3",
			"prod_class": "545",
			"base_tp": "74.96",
			"base_vat": "13.04",
			"prod_name": "Florocin Pellets for Suspension",
			"prod_code": "FCP3",
			"code_id": null,
			"com_pack_size": "60 ml",
			"com_pack_desc": "1X1's",
			"base_uom": "BOX",
			"req_current_stock": 2040,
			"req_safety_stock": 100
		},
		{
			"id": 19,
			"prod_id": "1019",
			"display_code": "BST2",
			"prod_class": "546",
			"base_tp": "225.56",
			"base_vat": "39.25",
			"prod_name": "Bisopress 5 Tablet",
			"prod_code": "BST2",
			"code_id": null,
			"com_pack_size": "30's",
			"com_pack_desc": "3X10's",
			"base_uom": "BOX",
			"req_current_stock": 2045.94,
			"req_safety_stock": 100
		},
		{
			"id": 59,
			"prod_id": "1059",
			"display_code": "FVT1",
			"prod_class": "546",
			"base_tp": "150.3",
			"base_vat": "26.15",
			"prod_name": "Flexivan Tablet",
			"prod_code": "FVT1",
			"code_id": null,
			"com_pack_size": "50's",
			"com_pack_desc": "5X10's",
			"base_uom": "BOX",
			"req_current_stock": 2054,
			"req_safety_stock": 100
		},
		{
			"id": 15,
			"prod_id": "1015",
			"display_code": "ACP2",
			"prod_class": "546",
			"base_tp": "97.74",
			"base_vat": "17.01",
			"prod_name": "Azaltic PFS",
			"prod_code": "ACP2",
			"code_id": null,
			"com_pack_size": "35 ml",
			"com_pack_desc": "1X1's",
			"base_uom": "BOX",
			"req_current_stock": 2056,
			"req_safety_stock": 100
		},
		{
			"id": 95,
			"prod_id": "1095",
			"display_code": "NSS1",
			"prod_class": "550",
			"base_tp": "60.15",
			"base_vat": "10.47",
			"prod_name": "Nipro Seas Syrup",
			"prod_code": "NSS1",
			"code_id": null,
			"com_pack_size": "100 ml",
			"com_pack_desc": "1X1's",
			"base_uom": "BOX",
			"req_current_stock": 2069,
			"req_safety_stock": 100
		},
		{
			"id": 45,
			"prod_id": "1045",
			"display_code": "ERC1",
			"prod_class": "550",
			"base_tp": "262.37",
			"base_vat": "45.65",
			"prod_name": "Esotor 20 Capsule",
			"prod_code": "ERC1",
			"code_id": null,
			"com_pack_size": "50's",
			"com_pack_desc": "5X10's",
			"base_uom": "BOX",
			"req_current_stock": 2080,
			"req_safety_stock": 100
		},
		{
			"id": 128,
			"prod_id": "1128",
			"display_code": "RDT1",
			"prod_class": "546",
			"base_tp": "225.56",
			"base_vat": "39.25",
			"prod_name": "Rupatid Tablet",
			"prod_code": "RDT1",
			"code_id": null,
			"com_pack_size": "30's",
			"com_pack_desc": "3X10's",
			"base_uom": "BOX",
			"req_current_stock": 2081.01,
			"req_safety_stock": 100
		},
		{
			"id": 14,
			"prod_id": "1014",
			"display_code": "ACP1",
			"prod_class": "546",
			"base_tp": "63.72",
			"base_vat": "11.09",
			"prod_name": "Azaltic PFS",
			"prod_code": "ACP1",
			"code_id": null,
			"com_pack_size": "15 ml",
			"com_pack_desc": "1X1's",
			"base_uom": "BOX",
			"req_current_stock": 2089,
			"req_safety_stock": 100
		},
		{
			"id": 21,
			"prod_id": "1021",
			"display_code": "CSC1",
			"prod_class": "546",
			"base_tp": "71.21",
			"base_vat": "12.39",
			"prod_name": "Camphor Plus Cream",
			"prod_code": "CSC1",
			"code_id": null,
			"com_pack_size": "15 gm",
			"com_pack_desc": "1X1's",
			"base_uom": "BOX",
			"req_current_stock": 2115,
			"req_safety_stock": 100
		},
		{
			"id": 93,
			"prod_id": "1093",
			"display_code": "NNS1",
			"prod_class": "546",
			"base_tp": "26.32",
			"base_vat": "4.58",
			"prod_name": "Nipozin Syrup",
			"prod_code": "NNS1",
			"code_id": null,
			"com_pack_size": "100 ml",
			"com_pack_desc": "1X1's",
			"base_uom": "BOX",
			"req_current_stock": 2123,
			"req_safety_stock": 100
		},
		{
			"id": 137,
			"prod_id": "1137",
			"display_code": "TVT1",
			"prod_class": "546",
			"base_tp": "338.68",
			"base_vat": "58.93",
			"prod_name": "Toplevo 500 Tablet",
			"prod_code": "TVT1",
			"code_id": null,
			"com_pack_size": "30's",
			"com_pack_desc": "3X10's",
			"base_uom": "BOX",
			"req_current_stock": 2155.33,
			"req_safety_stock": 100
		},
		{
			"id": 18,
			"prod_id": "1018",
			"display_code": "BST1",
			"prod_class": "550",
			"base_tp": "135.38",
			"base_vat": "23.56",
			"prod_name": "Bisopress 2.5 Tablet",
			"prod_code": "BST1",
			"code_id": null,
			"com_pack_size": "30's",
			"com_pack_desc": "3X10's",
			"base_uom": "BOX",
			"req_current_stock": 2156.807,
			"req_safety_stock": 100
		},
		{
			"id": 26,
			"prod_id": "1026",
			"display_code": "CFC2",
			"prod_class": "550",
			"base_tp": "226.51",
			"base_vat": "39.41",
			"prod_name": "Cefracef 500 Capsule",
			"prod_code": "CFC2",
			"code_id": null,
			"com_pack_size": "24's",
			"com_pack_desc": "6X4's",
			"base_uom": "BOX",
			"req_current_stock": 2203.17,
			"req_safety_stock": 100
		},
		{
			"id": 142,
			"prod_id": "1142",
			"display_code": "VST1",
			"prod_class": "541",
			"base_tp": "150.3",
			"base_vat": "26.15",
			"prod_name": "Visnil Tablet",
			"prod_code": "VST1",
			"code_id": null,
			"com_pack_size": "50's",
			"com_pack_desc": "5X10's",
			"base_uom": "BOX",
			"req_current_stock": 2206,
			"req_safety_stock": 100
		},
		{
			"id": 29,
			"prod_id": "1029",
			"display_code": "CXT1",
			"prod_class": "546",
			"base_tp": "105.28",
			"base_vat": "18.32",
			"prod_name": "Cialix 10 Tablet",
			"prod_code": "CXT1",
			"code_id": null,
			"com_pack_size": "4's",
			"com_pack_desc": "1X4's",
			"base_uom": "BOX",
			"req_current_stock": 2281,
			"req_safety_stock": 100
		},
		{
			"id": 109,
			"prod_id": "1109",
			"display_code": "ONC3",
			"prod_class": "542",
			"base_tp": "187.41",
			"base_vat": "32.61",
			"prod_name": "Omecron 20 Capsule",
			"prod_code": "ONC3",
			"code_id": null,
			"com_pack_size": "50's",
			"com_pack_desc": "5X10's",
			"base_uom": "BOX",
			"req_current_stock": 2330,
			"req_safety_stock": 100
		},
		{
			"id": 94,
			"prod_id": "1094",
			"display_code": "NDT2",
			"prod_class": "542",
			"base_tp": "179.91",
			"base_vat": "31.3",
			"prod_name": "Nipro Gold Tablet",
			"prod_code": "NDT2",
			"code_id": null,
			"com_pack_size": "30's",
			"com_pack_desc": "2X15's",
			"base_uom": "BOX",
			"req_current_stock": 2331.03,
			"req_safety_stock": 100
		},
		{
			"id": 129,
			"prod_id": "1129",
			"display_code": "SDT3",
			"prod_class": "541",
			"base_tp": "314.84",
			"base_vat": "54.78",
			"prod_name": "Starcal D Tablet",
			"prod_code": "SDT3",
			"code_id": null,
			"com_pack_size": "60's",
			"com_pack_desc": "4X15's",
			"base_uom": "BOX",
			"req_current_stock": 2482.14,
			"req_safety_stock": 100
		},
		{
			"id": 77,
			"prod_id": "1077",
			"display_code": "LMX2",
			"prod_class": "546",
			"base_tp": "287.86",
			"base_vat": "50.09",
			"prod_name": "Lijenta-MX 5 Tablet",
			"prod_code": "LMX2",
			"code_id": null,
			"com_pack_size": "16's",
			"com_pack_desc": "2X8's",
			"base_uom": "BOX",
			"req_current_stock": 2847,
			"req_safety_stock": 100
		},
		{
			"id": 11,
			"prod_id": "1011",
			"display_code": "ART1",
			"prod_class": "550",
			"base_tp": "225.56",
			"base_vat": "39.25",
			"prod_name": "Avator 10 Tablet",
			"prod_code": "ART1",
			"code_id": null,
			"com_pack_size": "30's",
			"com_pack_desc": "3X10's",
			"base_uom": "BOX",
			"req_current_stock": 3020.12,
			"req_safety_stock": 100
		},
		{
			"id": 133,
			"prod_id": "1133",
			"display_code": "TST1",
			"prod_class": "546",
			"base_tp": "113.19",
			"base_vat": "19.7",
			"prod_name": "Tamino Plus Tablet",
			"prod_code": "TST1",
			"code_id": null,
			"com_pack_size": "100's",
			"com_pack_desc": "10X10's",
			"base_uom": "BOX",
			"req_current_stock": 3042,
			"req_safety_stock": 100
		},
		{
			"id": 68,
			"prod_id": "1068",
			"display_code": "HNP1",
			"prod_class": "546",
			"base_tp": "45.28",
			"base_vat": "7.88",
			"prod_name": "Halopen PFS",
			"prod_code": "HNP1",
			"code_id": null,
			"com_pack_size": "100 ml",
			"com_pack_desc": "1X1's",
			"base_uom": "BOX",
			"req_current_stock": 3045,
			"req_safety_stock": 100
		},
		{
			"id": 34,
			"prod_id": "1034",
			"display_code": "DDT1",
			"prod_class": "542",
			"base_tp": "225.64",
			"base_vat": "39.26",
			"prod_name": "Diazid 80 Tablet",
			"prod_code": "DDT1",
			"code_id": null,
			"com_pack_size": "50's",
			"com_pack_desc": "5X10's",
			"base_uom": "BOX",
			"req_current_stock": 3141.44,
			"req_safety_stock": 100
		},
		{
			"id": 58,
			"prod_id": "1058",
			"display_code": "FRT1",
			"prod_class": "541",
			"base_tp": "225.64",
			"base_vat": "39.26",
			"prod_name": "Flexivan ER Tablet",
			"prod_code": "FRT1",
			"code_id": null,
			"com_pack_size": "50's",
			"com_pack_desc": "5X10's",
			"base_uom": "BOX",
			"req_current_stock": 3281,
			"req_safety_stock": 100
		},
		{
			"id": 120,
			"prod_id": "1120",
			"display_code": "PTT1",
			"prod_class": "550",
			"base_tp": "151.42",
			"base_vat": "26.35",
			"prod_name": "Prokinet Tablet",
			"prod_code": "PTT1",
			"code_id": null,
			"com_pack_size": "100's",
			"com_pack_desc": "10X10's",
			"base_uom": "BOX",
			"req_current_stock": 3382,
			"req_safety_stock": 100
		},
		{
			"id": 138,
			"prod_id": "1138",
			"display_code": "TLT1",
			"prod_class": "550",
			"base_tp": "226.46",
			"base_vat": "39.4",
			"prod_name": "Toralin Tablet",
			"prod_code": "TLT1",
			"code_id": null,
			"com_pack_size": "30's",
			"com_pack_desc": "3X10's",
			"base_uom": "BOX",
			"req_current_stock": 3434.181,
			"req_safety_stock": 100
		},
		{
			"id": 79,
			"prod_id": "1079",
			"display_code": "LST3",
			"prod_class": "541",
			"base_tp": "215.52",
			"base_vat": "37.5",
			"prod_name": "Losarva 50 Tablet",
			"prod_code": "LST3",
			"code_id": null,
			"com_pack_size": "50's",
			"com_pack_desc": "5X10's",
			"base_uom": null,
			"req_current_stock": 3708,
			"req_safety_stock": 100
		},
		{
			"id": 9,
			"prod_id": "1009",
			"display_code": "ATT1",
			"prod_class": "550",
			"base_tp": "150.67",
			"base_vat": "26.22",
			"prod_name": "Arcet Tablet",
			"prod_code": "ATT1",
			"code_id": null,
			"com_pack_size": "100's",
			"com_pack_desc": "10X10's",
			"base_uom": "BOX",
			"req_current_stock": 4711,
			"req_safety_stock": 100
		},
		{
			"id": 46,
			"prod_id": "1046",
			"display_code": "ERT1",
			"prod_class": "550",
			"base_tp": "188.16",
			"base_vat": "32.74",
			"prod_name": "Esotor 20 Tablet",
			"prod_code": "ERT1",
			"code_id": null,
			"com_pack_size": "50's",
			"com_pack_desc": "5X10's",
			"base_uom": "BOX",
			"req_current_stock": 5302,
			"req_safety_stock": 100
		},
		{
			"id": 35,
			"prod_id": "1035",
			"display_code": "DVT5",
			"prod_class": "541",
			"base_tp": "449.78",
			"base_vat": "78.26",
			"prod_name": "Doxiva 200 Tablet",
			"prod_code": "DVT5",
			"code_id": null,
			"com_pack_size": "100's",
			"com_pack_desc": "10X10's",
			"base_uom": "BOX",
			"req_current_stock": 6401,
			"req_safety_stock": 100
		},
		{
			"id": 42,
			"prod_id": "1042",
			"display_code": "EPT2",
			"prod_class": "541",
			"base_tp": "374.81",
			"base_vat": "65.22",
			"prod_name": "Empa 25 Tablet",
			"prod_code": "EPT2",
			"code_id": null,
			"com_pack_size": "10's",
			"com_pack_desc": "1X10's",
			"base_uom": "BOX",
			"req_current_stock": 8397,
			"req_safety_stock": 100
		},
		{
			"id": 72,
			"prod_id": "1072",
			"display_code": "LTT2",
			"prod_class": "541",
			"base_tp": "494.75",
			"base_vat": "86.09",
			"prod_name": "Lijenta 5 Tablet",
			"prod_code": "LTT2",
			"code_id": null,
			"com_pack_size": "30's",
			"com_pack_desc": "2X15's",
			"base_uom": "BOX",
			"req_current_stock": 9427.33,
			"req_safety_stock": 100
		},
		{
			"id": 13,
			"prod_id": "1013",
			"display_code": "ACT4",
			"prod_class": "542",
			"base_tp": "314.84",
			"base_vat": "54.78",
			"prod_name": "Azaltic 500 Tablet",
			"prod_code": "ACT4",
			"code_id": null,
			"com_pack_size": "12's",
			"com_pack_desc": "4X3's",
			"base_uom": "BOX",
			"req_current_stock": 9512,
			"req_safety_stock": 100
		},
		{
			"id": 1012,
			"prod_id": "10000",
			"display_code": "CCT1",
			"prod_class": "546",
			"base_tp": "142.43",
			"base_vat": "24.78",
			"prod_name": "Citrux-C",
			"prod_code": "CCT1",
			"code_id": null,
			"com_pack_size": "100's",
			"com_pack_desc": "10x10's",
			"base_uom": null,
			"req_current_stock": 9850,
			"req_safety_stock": 100
		},
		{
			"id": 23,
			"prod_id": "1023",
			"display_code": "CVT1",
			"prod_class": "550",
			"base_tp": "224.89",
			"base_vat": "39.13",
			"prod_name": "Carceva 75 Tablet",
			"prod_code": "CVT1",
			"code_id": null,
			"com_pack_size": "30's",
			"com_pack_desc": "3X10's",
			"base_uom": "BOX",
			"req_current_stock": 9915,
			"req_safety_stock": 100
		},
		{
			"id": 105,
			"prod_id": "1105",
			"display_code": "NVI1",
			"prod_class": "546",
			"base_tp": "82.71",
			"base_vat": "14.39",
			"prod_name": "Nixon 250 mg IV Injection",
			"prod_code": "NVI1",
			"code_id": null,
			"com_pack_size": "1's",
			"com_pack_desc": "1X1's",
			"base_uom": "BOX",
			"req_current_stock": 9972,
			"req_safety_stock": 100
		},
		{
			"id": 130,
			"prod_id": "1130",
			"display_code": "SMT1",
			"prod_class": "546",
			"base_tp": "146.18",
			"base_vat": "25.44",
			"prod_name": "Starcal M Tablet",
			"prod_code": "SMT1",
			"code_id": null,
			"com_pack_size": "30's",
			"com_pack_desc": "2X15's",
			"base_uom": "BOX",
			"req_current_stock": 9974,
			"req_safety_stock": 100
		},
		{
			"id": 104,
			"prod_id": "1104",
			"display_code": "NMI1",
			"prod_class": "546",
			"base_tp": "82.71",
			"base_vat": "14.39",
			"prod_name": "Nixon 250 IM",
			"prod_code": "NMI1",
			"code_id": null,
			"com_pack_size": "1's",
			"com_pack_desc": "1X1's",
			"base_uom": "BOX",
			"req_current_stock": 9976,
			"req_safety_stock": 100
		},
		{
			"id": 1009,
			"prod_id": "1170",
			"display_code": "SCT1",
			"prod_class": "546",
			"base_tp": "187.41",
			"base_vat": "32.61",
			"prod_name": "Starcal Tablet",
			"prod_code": "SCT1",
			"code_id": null,
			"com_pack_size": "50's",
			"com_pack_desc": "5X10's",
			"base_uom": "BOX",
			"req_current_stock": 9979,
			"req_safety_stock": 100
		},
		{
			"id": 1008,
			"prod_id": "1169",
			"display_code": "STT1",
			"prod_class": "546",
			"base_tp": "180.36",
			"base_vat": "31.38",
			"prod_name": "Starcal D Forte Tablet",
			"prod_code": "STT1",
			"code_id": null,
			"com_pack_size": "30's",
			"com_pack_desc": "2X15's",
			"base_uom": "BOX",
			"req_current_stock": 9985,
			"req_safety_stock": 100
		},
		{
			"id": 140,
			"prod_id": "1140",
			"display_code": "VZS1",
			"prod_class": "546",
			"base_tp": "33.84",
			"base_vat": "5.89",
			"prod_name": "V4Z Syrup",
			"prod_code": "VZS1",
			"code_id": null,
			"com_pack_size": "100 ml",
			"com_pack_desc": "1X1's",
			"base_uom": "BOX",
			"req_current_stock": 9987,
			"req_safety_stock": 100
		},
		{
			"id": 1001,
			"prod_id": "1162",
			"display_code": "MLS1",
			"prod_class": "546",
			"base_tp": "30.07",
			"base_vat": "5.23",
			"prod_name": "Mucodil Syrup",
			"prod_code": "MLS1",
			"code_id": null,
			"com_pack_size": "100 ml",
			"com_pack_desc": "1X1's",
			"base_uom": "BOX",
			"req_current_stock": 9991,
			"req_safety_stock": 100
		},
		{
			"id": 693,
			"prod_id": "2013",
			"display_code": "FNT3",
			"prod_class": "546",
			"base_tp": "112.44",
			"base_vat": "19.56",
			"prod_name": "Fexten 60 Tablet",
			"prod_code": "FNT3",
			"code_id": null,
			"com_pack_size": "30's",
			"com_pack_desc": "3X10's",
			"base_uom": "BOX",
			"req_current_stock": 9993,
			"req_safety_stock": 100
		},
		{
			"id": 123,
			"prod_id": "1123",
			"display_code": "RCG2",
			"prod_class": "546",
			"base_tp": "224.89",
			"base_vat": "39.13",
			"prod_name": "Receca  30 GFS",
			"prod_code": "RCG2",
			"code_id": null,
			"com_pack_size": "30's",
			"com_pack_desc": "1X30's",
			"base_uom": "BOX",
			"req_current_stock": 9995,
			"req_safety_stock": 100
		},
		{
			"id": 151,
			"prod_id": "1151",
			"display_code": "BNC1",
			"prod_class": "546",
			"base_tp": "180.96",
			"base_vat": "31.49",
			"prod_name": "Bexen 500 Capsule",
			"prod_code": "BNC1",
			"code_id": null,
			"com_pack_size": "20's",
			"com_pack_desc": "5X4's",
			"base_uom": "BOX",
			"req_current_stock": 9996,
			"req_safety_stock": 100
		},
		{
			"id": 173,
			"prod_id": "1173",
			"display_code": "VPC2",
			"prod_class": "546",
			"base_tp": "210.49",
			"base_vat": "36.63",
			"prod_name": "Vegecap-E 400 Capsule",
			"prod_code": "VPC2",
			"code_id": null,
			"com_pack_size": "40's",
			"com_pack_desc": "4X10's",
			"base_uom": "BOX",
			"req_current_stock": 9997,
			"req_safety_stock": 100
		},
		{
			"id": 172,
			"prod_id": "1172",
			"display_code": "VPC1",
			"prod_class": "546",
			"base_tp": "188.16",
			"base_vat": "32.74",
			"prod_name": "Vegecap-E 200 Capsule",
			"prod_code": "VPC1",
			"code_id": null,
			"com_pack_size": "50's",
			"com_pack_desc": "5X10's",
			"base_uom": "BOX",
			"req_current_stock": 9998,
			"req_safety_stock": 100
		},
		{
			"id": 175,
			"prod_id": "1175",
			"display_code": "VLT1",
			"prod_class": "546",
			"base_tp": "132.31",
			"base_vat": "23.02",
			"prod_name": "Vermikil Tablet",
			"prod_code": "VLT1",
			"code_id": null,
			"com_pack_size": "50's",
			"com_pack_desc": "25X2's",
			"base_uom": "BOX",
			"req_current_stock": 9998,
			"req_safety_stock": 100
		},
		{
			"id": 1006,
			"prod_id": "1167",
			"display_code": "RNT1",
			"prod_class": "546",
			"base_tp": "180.36",
			"base_vat": "31.38",
			"prod_name": "Reflexen 10 Tablet",
			"prod_code": "RNT1",
			"code_id": null,
			"com_pack_size": "30's",
			"com_pack_desc": "3X10's",
			"base_uom": "BOX",
			"req_current_stock": 9998,
			"req_safety_stock": 100
		},
		{
			"id": 1002,
			"prod_id": "1163",
			"display_code": "NLT1",
			"prod_class": "546",
			"base_tp": "112.44",
			"base_vat": "19.56",
			"prod_name": "Nacsol Tablet",
			"prod_code": "NLT1",
			"code_id": null,
			"com_pack_size": "10's",
			"com_pack_desc": "1x10's",
			"base_uom": "BOX",
			"req_current_stock": 9998,
			"req_safety_stock": 100
		},
		{
			"id": 99,
			"prod_id": "1099",
			"display_code": "NDP1",
			"prod_class": "546",
			"base_tp": "26.32",
			"base_vat": "4.58",
			"prod_name": "Nitide PFS",
			"prod_code": "NDP1",
			"code_id": null,
			"com_pack_size": "30 ml",
			"com_pack_desc": "1X1's",
			"base_uom": "BOX",
			"req_current_stock": 9998,
			"req_safety_stock": 100
		},
		{
			"id": 1010,
			"prod_id": "1160",
			"display_code": "MST1",
			"prod_class": "546",
			"base_tp": "131.19",
			"base_vat": "22.83",
			"prod_name": "Mecliz Plus Tablet",
			"prod_code": "MST1",
			"code_id": null,
			"com_pack_size": "50's",
			"com_pack_desc": "5X10's",
			"base_uom": "BOX",
			"req_current_stock": 9998,
			"req_safety_stock": 100
		},
		{
			"id": 156,
			"prod_id": "1156",
			"display_code": "GBS1",
			"prod_class": "546",
			"base_tp": "33.97",
			"base_vat": "5.91",
			"prod_name": "Gastab Syrup",
			"prod_code": "GBS1",
			"code_id": null,
			"com_pack_size": "100 ml",
			"com_pack_desc": "1X1's",
			"base_uom": "BOX",
			"req_current_stock": 9999,
			"req_safety_stock": 100
		},
		{
			"id": 153,
			"prod_id": "1153",
			"display_code": "DNT1",
			"prod_class": "546",
			"base_tp": "112.82",
			"base_vat": "19.63",
			"prod_name": "Dmigrain 0.5 Tablet",
			"prod_code": "DNT1",
			"code_id": null,
			"com_pack_size": "50's",
			"com_pack_desc": "5X10's",
			"base_uom": "BOX",
			"req_current_stock": 9999,
			"req_safety_stock": 100
		},
		{
			"id": 157,
			"prod_id": "1157",
			"display_code": "GBT1",
			"prod_class": "546",
			"base_tp": "150.67",
			"base_vat": "26.22",
			"prod_name": "Gastab Tablet",
			"prod_code": "GBT1",
			"code_id": null,
			"com_pack_size": "100's",
			"com_pack_desc": "10X10's",
			"base_uom": "BOX",
			"req_current_stock": 9999,
			"req_safety_stock": 100
		},
		{
			"id": 154,
			"prod_id": "1154",
			"display_code": "DNT2",
			"prod_class": "546",
			"base_tp": "263.12",
			"base_vat": "45.78",
			"prod_name": "Dmigrain 1.5 Tablet",
			"prod_code": "DNT2",
			"code_id": null,
			"com_pack_size": "50's",
			"com_pack_desc": "5X10's",
			"base_uom": "BOX",
			"req_current_stock": 9999,
			"req_safety_stock": 100
		},
		{
			"id": 1011,
			"prod_id": "1159",
			"display_code": "IRT1",
			"prod_class": "546",
			"base_tp": "113.57",
			"base_vat": "19.76",
			"prod_name": "Itchlor Tablet",
			"prod_code": "IRT1",
			"code_id": null,
			"com_pack_size": "50's",
			"com_pack_desc": "5X10's",
			"base_uom": "BOX",
			"req_current_stock": 9999,
			"req_safety_stock": 100
		},
		{
			"id": 171,
			"prod_id": "1171",
			"display_code": "TXT1",
			"prod_class": "546",
			"base_tp": "224.89",
			"base_vat": "39.13",
			"prod_name": "Topmox 400 Tablet",
			"prod_code": "TXT1",
			"code_id": null,
			"com_pack_size": "10's",
			"com_pack_desc": "1X10's",
			"base_uom": "BOX",
			"req_current_stock": 10000,
			"req_safety_stock": 100
		},
		{
			"id": 690,
			"prod_id": "2010",
			"display_code": "RVI1",
			"prod_class": "546",
			"base_tp": "93.7",
			"base_vat": "16.3",
			"prod_name": "Roxecf 750 mg IM/IV Injection",
			"prod_code": "RVI1",
			"code_id": null,
			"com_pack_size": "1's",
			"com_pack_desc": "1X1's",
			"base_uom": "BOX",
			"req_current_stock": 10000,
			"req_safety_stock": 100
		},
		{
			"id": 689,
			"prod_id": "2009",
			"display_code": "NNT1",
			"prod_class": "546",
			"base_tp": "188.16",
			"base_vat": "32.74",
			"prod_name": "Nipoxen 250 Tablet",
			"prod_code": "NNT1",
			"code_id": null,
			"com_pack_size": "50's",
			"com_pack_desc": "5X10's",
			"base_uom": "BOX",
			"req_current_stock": 10000,
			"req_safety_stock": 100
		},
		{
			"id": 688,
			"prod_id": "2008",
			"display_code": "RFT1",
			"prod_class": "546",
			"base_tp": "225.61",
			"base_vat": "39.26",
			"prod_name": "Roxcef 250 mg Tablet",
			"prod_code": "RFT1",
			"code_id": null,
			"com_pack_size": "12's",
			"com_pack_desc": "2X6's",
			"base_uom": "BOX",
			"req_current_stock": 10000,
			"req_safety_stock": 100
		},
		{
			"id": 71,
			"prod_id": "1071",
			"display_code": "ILS1",
			"prod_class": "546",
			"base_tp": "31.58",
			"base_vat": "5.49",
			"prod_name": "Isosal Syrup",
			"prod_code": "ILS1",
			"code_id": null,
			"com_pack_size": "100 ml",
			"com_pack_desc": "1X1's",
			"base_uom": "BOX",
			"req_current_stock": 10000,
			"req_safety_stock": 100
		},
		{
			"id": 691,
			"prod_id": "2011",
			"display_code": "RVI2",
			"prod_class": "546",
			"base_tp": "149.93",
			"base_vat": "26.09",
			"prod_name": "Roxcef 1.5 mg IV Injection",
			"prod_code": "RVI2",
			"code_id": null,
			"com_pack_size": "1's",
			"com_pack_desc": "1X1's",
			"base_uom": "BOX",
			"req_current_stock": 10000,
			"req_safety_stock": 100
		},
		{
			"id": 92,
			"prod_id": "1092",
			"display_code": "NRT1",
			"prod_class": "546",
			"base_tp": "315.74",
			"base_vat": "54.94",
			"prod_name": "Nipoxen 500 SR Tablet",
			"prod_code": "NRT1",
			"code_id": null,
			"com_pack_size": "30's",
			"com_pack_desc": "3X10's",
			"base_uom": "BOX",
			"req_current_stock": 10000,
			"req_safety_stock": 100
		},
		{
			"id": 695,
			"prod_id": "2015",
			"display_code": "RFT2",
			"prod_class": "546",
			"base_tp": "203.03",
			"base_vat": "35.33",
			"prod_name": "Roxcef 500 mg Tablet",
			"prod_code": "RFT2",
			"code_id": null,
			"com_pack_size": "6's",
			"com_pack_desc": "1X6's",
			"base_uom": "BOX",
			"req_current_stock": 10000,
			"req_safety_stock": 100
		},
		{
			"id": 150,
			"prod_id": "1150",
			"display_code": "ALT1",
			"prod_class": "546",
			"base_tp": "188.16",
			"base_vat": "32.74",
			"prod_name": "Anxionil Tablet",
			"prod_code": "ALT1",
			"code_id": null,
			"com_pack_size": "50's",
			"com_pack_desc": "5X10's",
			"base_uom": "BOX",
			"req_current_stock": 10000,
			"req_safety_stock": 100
		},
		{
			"id": 100,
			"prod_id": "1100",
			"display_code": "NDP2",
			"prod_class": "546",
			"base_tp": "37.59",
			"base_vat": "6.54",
			"prod_name": "Nitide PFS",
			"prod_code": "NDP2",
			"code_id": null,
			"com_pack_size": "60 ml",
			"com_pack_desc": "1X1's",
			"base_uom": "BOX",
			"req_current_stock": 10000,
			"req_safety_stock": 100
		},
		{
			"id": 1007,
			"prod_id": "1168",
			"display_code": "RNT2",
			"prod_class": "546",
			"base_tp": "451.12",
			"base_vat": "78.49",
			"prod_name": "Reflexen 25 Tablet",
			"prod_code": "RNT2",
			"code_id": null,
			"com_pack_size": "30's",
			"com_pack_desc": "3X10's",
			"base_uom": "BOX",
			"req_current_stock": 10000,
			"req_safety_stock": 100
		},
		{
			"id": 1005,
			"prod_id": "1166",
			"display_code": "PNS1",
			"prod_class": "546",
			"base_tp": "37.59",
			"base_vat": "6.54",
			"prod_name": "Polytamin Syrup",
			"prod_code": "PNS1",
			"code_id": null,
			"com_pack_size": "100 ml",
			"com_pack_desc": "1x1's",
			"base_uom": "BOX",
			"req_current_stock": 10000,
			"req_safety_stock": 100
		},
		{
			"id": 1004,
			"prod_id": "1165",
			"display_code": "OQC2",
			"prod_class": "546",
			"base_tp": "270.61",
			"base_vat": "47.09",
			"prod_name": "Oxi-Q 60 Capsule",
			"prod_code": "OQC2",
			"code_id": null,
			"com_pack_size": "20's",
			"com_pack_desc": "2X10's",
			"base_uom": "BOX",
			"req_current_stock": 10000,
			"req_safety_stock": 100
		},
		{
			"id": 1003,
			"prod_id": "1164",
			"display_code": "OQC1",
			"prod_class": "546",
			"base_tp": "270.77",
			"base_vat": "47.11",
			"prod_name": "Oxi-Q 30 Capsule",
			"prod_code": "OQC1",
			"code_id": null,
			"com_pack_size": "30's",
			"com_pack_desc": "3X10's",
			"base_uom": "BOX",
			"req_current_stock": 10000,
			"req_safety_stock": 100
		},
		{
			"id": 143,
			"prod_id": "1143",
			"display_code": "VRC1",
			"prod_class": "546",
			"base_tp": "112.82",
			"base_vat": "19.63",
			"prod_name": "Vurdon SR Capsule",
			"prod_code": "VRC1",
			"code_id": null,
			"com_pack_size": "50's",
			"com_pack_desc": "5X10's",
			"base_uom": "BOX",
			"req_current_stock": 10000,
			"req_safety_stock": 100
		},
		{
			"id": 144,
			"prod_id": "1144",
			"display_code": "XVI2",
			"prod_class": "546",
			"base_tp": "149.93",
			"base_vat": "26.09",
			"prod_name": "Xinarox 1.5 g IV Injection",
			"prod_code": "XVI2",
			"code_id": null,
			"com_pack_size": "1's",
			"com_pack_desc": "1X1's",
			"base_uom": "BOX",
			"req_current_stock": 10000,
			"req_safety_stock": 100
		},
		{
			"id": 176,
			"prod_id": "1176",
			"display_code": "XNT1",
			"prod_class": "546",
			"base_tp": "150.37",
			"base_vat": "26.16",
			"prod_name": "Xifamin 200 Tablet",
			"prod_code": "XNT1",
			"code_id": null,
			"com_pack_size": "10's",
			"com_pack_desc": "1X10's",
			"base_uom": "BOX",
			"req_current_stock": 10000,
			"req_safety_stock": 100
		},
		{
			"id": 174,
			"prod_id": "1174",
			"display_code": "VLS1",
			"prod_class": "546",
			"base_tp": "11.33",
			"base_vat": "1.97",
			"prod_name": "Vermikil Suspension",
			"prod_code": "VLS1",
			"code_id": null,
			"com_pack_size": "10 ml",
			"com_pack_desc": "1X1's",
			"base_uom": "BOX",
			"req_current_stock": 10000,
			"req_safety_stock": 100
		},
		{
			"id": 158,
			"prod_id": "1158",
			"display_code": "IRS1",
			"prod_class": "546",
			"base_tp": "22.65",
			"base_vat": "3.94",
			"prod_name": "Itchlor Syrup",
			"prod_code": "IRS1",
			"code_id": null,
			"com_pack_size": "60 ml",
			"com_pack_desc": "1X1's",
			"base_uom": "BOX",
			"req_current_stock": 10000,
			"req_safety_stock": 100
		},
		{
			"id": 152,
			"prod_id": "1152",
			"display_code": "BNP1",
			"prod_class": "546",
			"base_tp": "52.47",
			"base_vat": "9.13",
			"prod_name": "Bexen PFS",
			"prod_code": "BNP1",
			"code_id": null,
			"com_pack_size": "100 ml",
			"com_pack_desc": "1X1's",
			"base_uom": "BOX",
			"req_current_stock": 10000,
			"req_safety_stock": 100
		},
		{
			"id": 1000,
			"prod_id": "1161",
			"display_code": "MLT1",
			"prod_class": "546",
			"base_tp": "262.37",
			"base_vat": "45.65",
			"prod_name": "Mesala 400 Tablet",
			"prod_code": "MLT1",
			"code_id": null,
			"com_pack_size": "50's",
			"com_pack_desc": "5X10's",
			"base_uom": "BOX",
			"req_current_stock": 10000,
			"req_safety_stock": 100
		}
	]
}